name: 'Create Environment'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name (e.g. dev, staging, production, loadtest)'
        required: true
        type: string
      app_memory:
        description: "App Memory (normally '256M' for test environments, '1G' for production)"
        required: true
        type: string

jobs:
  create_environment:
    name: 'Create Environment'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Install the Cloud Foundry CLI'
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli

      - name: 'Login to Gov.UK PaaS'
        run: |
          cf login -a api.london.cloud.service.gov.uk -u ${{ secrets.CF_USERNAME }} -p '${{ secrets.CF_PASSWORD }}' -o 'co-equality-data-platform' -s 'sandbox'

      - name: 'Create Environment'
        env:
          PAAS_ENV_SHORTNAME: ${{ github.event.inputs.environment }}
          APP_MEMORY: ${{ github.event.inputs.app_memory }}
        run: bash ./CreateEnvironment.sh
        working-directory: ./hosting
