name: 'Maintenance Mode'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
        - 'dev'
        - 'staging'
        - 'production'
        default: 'dev'
      maintenance_mode_value:
        description: 'Maintenance Mode (ON or OFF)'
        required: true
        type: choice
        options:
        - 'ON'
        - 'OFF'
        default: 'OFF'

jobs:
  maintenance_mode:
    name: 'Turn Maintenance Mode ON or OFF'
    runs-on: ubuntu-latest

    steps:
      - name: 'Install the Cloud Foundry CLI'
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli

      - name: 'Login to Gov.UK PaaS'
        run: |
          cf login -a api.london.cloud.service.gov.uk -u ${{ secrets.CF_USERNAME }} -p '${{ secrets.CF_PASSWORD }}' -o 'co-equality-data-platform' -s 'sandbox'

      - name: 'Turn Maintenance Mode ON or OFF on DEV environment'
        if:  ${{ github.event.inputs.environment == 'dev' }}
        run: |
          cf target -s 'edp-dev'
          cf set-env 'equality-data-platform-dev' MAINTENANCE_MODE ${{ github.event.inputs.maintenance_mode_value }}
          cf restart 'equality-data-platform-dev' --strategy rolling

      - name: 'Turn Maintenance Mode ON or OFF on STAGING environment'
        if:  ${{ github.event.inputs.environment == 'staging' }}
        run: |
          cf target -s 'edp-staging'
          cf set-env 'equality-data-platform-staging' MAINTENANCE_MODE ${{ github.event.inputs.maintenance_mode_value }}
          cf restart 'equality-data-platform-staging' --strategy rolling

      - name: 'Turn Maintenance Mode ON or OFF on PRODUCTION environment'
        if:  ${{ github.event.inputs.environment == 'production' }}
        run: |
          cf target -s 'edp-production'
          cf set-env 'equality-data-platform-production' MAINTENANCE_MODE ${{ github.event.inputs.maintenance_mode_value }}
          cf restart 'equality-data-platform-production' --strategy rolling
